import type { Recipe } from './types';

/**
 * Returns 10 realistic sample recipes. Each call generates new recipes with unique IDs
 * so they can be loaded multiple times for testing (e.g. each click adds 10 more).
 */
export function getDefaultRecipes(): Recipe[] {
  const idPrefix = `sample-${Date.now()}-`;
  const recipes: Omit<Recipe, 'id'>[] = [
    {
      name: 'Chicken Stir-Fry',
      description: 'Quick and colorful chicken stir-fry with bell peppers and broccoli in a savory soy-ginger sauce.',
      ingredients: [
        { name: 'chicken breast', amount: '1', unit: 'lb' },
        { name: 'bell peppers', amount: '2', unit: 'medium' },
        { name: 'broccoli florets', amount: '2', unit: 'cups' },
        { name: 'soy sauce', amount: '3', unit: 'tbsp' },
        { name: 'fresh ginger', amount: '1', unit: 'tbsp' },
        { name: 'garlic', amount: '2', unit: 'cloves' },
        { name: 'vegetable oil', amount: '2', unit: 'tbsp' },
        { name: 'sesame oil', amount: '1', unit: 'tsp' },
      ],
      instructions: [
        'Slice chicken into thin strips. Cut bell peppers and broccoli into bite-sized pieces.',
        'Heat vegetable oil in a large wok or skillet over high heat. Add chicken and cook until golden, 4–5 minutes. Set aside.',
        'In the same pan, add a bit more oil. Stir-fry garlic and ginger for 30 seconds, then add vegetables. Cook 3–4 minutes until crisp-tender.',
        'Return chicken to the pan. Add soy sauce and sesame oil. Toss everything together for 1–2 minutes. Serve over rice.',
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 12,
      numOfServings: 4,
      difficulty: 'Easy',
      proteinTypes: ['chicken'],
      mealTypes: ['dinner'],
      cookingMethods: ['stove'],
      dietaryTags: [],
      tags: ['quick', 'healthy', 'weeknight'],
    },
    {
      name: 'Beef Tacos',
      description: 'Classic ground beef tacos with seasoned meat, fresh toppings, and soft or crunchy shells.',
      ingredients: [
        { name: 'ground beef', amount: '1', unit: 'lb' },
        { name: 'taco seasoning', amount: '2', unit: 'tbsp' },
        { name: 'onion', amount: '1', unit: 'medium' },
        { name: 'tortillas', amount: '8', unit: 'small' },
        { name: 'lettuce', amount: '2', unit: 'cups' },
        { name: 'cheddar cheese', amount: '1', unit: 'cup' },
        { name: 'sour cream', amount: '1/2', unit: 'cup' },
        { name: 'lime', amount: '1', unit: 'whole' },
      ],
      instructions: [
        'Dice the onion. Brown ground beef in a large skillet over medium-high heat, breaking up with a spoon. Add onion and cook until softened.',
        'Stir in taco seasoning and 1/2 cup water. Simmer 5 minutes until thickened.',
        'Warm tortillas according to package. Shred lettuce and grate cheese.',
        'Fill tortillas with beef, lettuce, cheese, sour cream, and a squeeze of lime.',
      ],
      prepTimeMinutes: 10,
      cookTimeMinutes: 15,
      numOfServings: 4,
      difficulty: 'Easy',
      proteinTypes: ['beef'],
      mealTypes: ['dinner'],
      cookingMethods: ['stove'],
      dietaryTags: [],
      tags: ['family-friendly', 'quick'],
    },
    {
      name: 'Oatmeal with Berries',
      description: 'Creamy stovetop oatmeal topped with mixed berries, honey, and a pinch of cinnamon.',
      ingredients: [
        { name: 'rolled oats', amount: '1', unit: 'cup' },
        { name: 'milk', amount: '2', unit: 'cups' },
        { name: 'mixed berries', amount: '1', unit: 'cup' },
        { name: 'honey', amount: '2', unit: 'tbsp' },
        { name: 'cinnamon', amount: '1/4', unit: 'tsp' },
        { name: 'pinch of salt', amount: '1', unit: 'pinch' },
      ],
      instructions: [
        'Combine oats, milk, and salt in a saucepan. Bring to a gentle boil, then reduce heat to low.',
        'Stir occasionally and cook 5–7 minutes until thick and creamy.',
        'Divide into bowls. Top with berries, drizzle with honey, and sprinkle with cinnamon.',
      ],
      prepTimeMinutes: 2,
      cookTimeMinutes: 8,
      numOfServings: 2,
      difficulty: 'Easy',
      proteinTypes: ['other'],
      mealTypes: ['breakfast'],
      cookingMethods: ['stove'],
      dietaryTags: ['healthy'],
      tags: ['breakfast', 'quick', 'healthy'],
    },
    {
      name: 'Grilled Salmon with Herbs',
      description: 'Pan-seared or grilled salmon fillets with lemon, dill, and a touch of garlic.',
      ingredients: [
        { name: 'salmon fillets', amount: '4', unit: 'fillets' },
        { name: 'olive oil', amount: '2', unit: 'tbsp' },
        { name: 'fresh dill', amount: '2', unit: 'tbsp' },
        { name: 'lemon', amount: '1', unit: 'whole' },
        { name: 'garlic', amount: '2', unit: 'cloves' },
        { name: 'salt and pepper', amount: 'to taste', unit: '' },
      ],
      instructions: [
        'Pat salmon dry. Rub with olive oil, minced garlic, chopped dill, salt, and pepper.',
        'Heat a grill or skillet over medium-high. Place salmon skin-side up and cook 4–5 minutes.',
        'Flip and cook 3–4 minutes until opaque and flaky. Squeeze lemon over before serving.',
      ],
      prepTimeMinutes: 10,
      cookTimeMinutes: 10,
      numOfServings: 4,
      difficulty: 'Medium',
      proteinTypes: ['fish'],
      mealTypes: ['dinner'],
      cookingMethods: ['stove'],
      dietaryTags: ['healthy'],
      tags: ['healthy', 'omega-3'],
    },
    {
      name: 'Lentil Soup',
      description: 'Hearty vegetarian lentil soup with carrots, celery, and warming spices.',
      ingredients: [
        { name: 'brown lentils', amount: '1', unit: 'cup' },
        { name: 'onion', amount: '1', unit: 'medium' },
        { name: 'carrots', amount: '2', unit: 'medium' },
        { name: 'celery', amount: '2', unit: 'stalks' },
        { name: 'vegetable broth', amount: '4', unit: 'cups' },
        { name: 'cumin', amount: '1', unit: 'tsp' },
        { name: 'turmeric', amount: '1/2', unit: 'tsp' },
        { name: 'olive oil', amount: '2', unit: 'tbsp' },
      ],
      instructions: [
        'Dice onion, carrots, and celery. Rinse lentils.',
        'Heat olive oil in a pot. Sauté onion, carrots, and celery 5 minutes. Add cumin and turmeric; stir 1 minute.',
        'Add lentils and broth. Bring to a boil, then simmer 25–30 minutes until lentils are tender.',
        'Season with salt and pepper. Serve with bread if desired.',
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 35,
      numOfServings: 4,
      difficulty: 'Easy',
      proteinTypes: ['other'],
      mealTypes: ['lunch', 'dinner'],
      cookingMethods: ['stove'],
      dietaryTags: ['vegetarian', 'healthy'],
      tags: ['soup', 'vegetarian', 'comfort food'],
    },
    {
      name: 'Spaghetti Bolognese',
      description: 'Classic Italian meat sauce with tomatoes, herbs, and Parmesan over spaghetti.',
      ingredients: [
        { name: 'ground beef', amount: '1', unit: 'lb' },
        { name: 'spaghetti', amount: '1', unit: 'lb' },
        { name: 'crushed tomatoes', amount: '28', unit: 'oz' },
        { name: 'onion', amount: '1', unit: 'medium' },
        { name: 'garlic', amount: '3', unit: 'cloves' },
        { name: 'olive oil', amount: '2', unit: 'tbsp' },
        { name: 'oregano', amount: '1', unit: 'tsp' },
        { name: 'Parmesan', amount: '1/2', unit: 'cup' },
      ],
      instructions: [
        'Dice onion and mince garlic. Heat olive oil in a large pot; sauté onion and garlic until soft.',
        'Add ground beef and brown, breaking up with a spoon. Stir in crushed tomatoes and oregano. Simmer 30–45 minutes.',
        'Cook spaghetti in salted boiling water according to package. Drain.',
        'Toss spaghetti with sauce. Serve with grated Parmesan.',
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 50,
      numOfServings: 6,
      difficulty: 'Medium',
      proteinTypes: ['beef'],
      mealTypes: ['dinner'],
      cookingMethods: ['stove'],
      dietaryTags: [],
      tags: ['classic', 'comfort food'],
    },
    {
      name: 'Greek Salad with Grilled Chicken',
      description: 'Fresh cucumber, tomato, red onion, olives, and feta with lemon-oregano chicken.',
      ingredients: [
        { name: 'chicken breast', amount: '2', unit: 'large' },
        { name: 'cucumber', amount: '1', unit: 'large' },
        { name: 'tomatoes', amount: '3', unit: 'medium' },
        { name: 'red onion', amount: '1/2', unit: 'medium' },
        { name: 'Kalamata olives', amount: '1/2', unit: 'cup' },
        { name: 'feta cheese', amount: '4', unit: 'oz' },
        { name: 'olive oil', amount: '3', unit: 'tbsp' },
        { name: 'lemon juice', amount: '2', unit: 'tbsp' },
        { name: 'oregano', amount: '1', unit: 'tsp' },
      ],
      instructions: [
        'Season chicken with olive oil, lemon juice, oregano, salt, and pepper. Grill or pan-fry until cooked through; slice.',
        'Chop cucumber, tomatoes, and red onion. Combine in a large bowl with olives and cubed feta.',
        'Whisk remaining olive oil and lemon juice; pour over salad. Add salt and pepper.',
        'Top with sliced chicken and serve.',
      ],
      prepTimeMinutes: 20,
      cookTimeMinutes: 12,
      numOfServings: 4,
      difficulty: 'Easy',
      proteinTypes: ['chicken'],
      mealTypes: ['lunch', 'dinner'],
      cookingMethods: ['stove', 'no bake'],
      dietaryTags: ['healthy'],
      tags: ['salad', 'mediterranean', 'light'],
    },
    {
      name: 'Vegetable Curry',
      description: 'Creamy coconut curry with cauliflower, chickpeas, and spinach over rice.',
      ingredients: [
        { name: 'cauliflower', amount: '1', unit: 'head' },
        { name: 'chickpeas', amount: '1', unit: 'can' },
        { name: 'coconut milk', amount: '1', unit: 'can' },
        { name: 'curry paste', amount: '2', unit: 'tbsp' },
        { name: 'spinach', amount: '2', unit: 'cups' },
        { name: 'onion', amount: '1', unit: 'medium' },
        { name: 'ginger', amount: '1', unit: 'tbsp' },
        { name: 'rice', amount: '1.5', unit: 'cups' },
      ],
      instructions: [
        'Cook rice according to package. Cut cauliflower into florets. Drain chickpeas.',
        'Sauté diced onion and ginger in a large pot. Add curry paste and cook 1 minute.',
        'Add cauliflower, chickpeas, and coconut milk. Simmer 15–20 minutes until cauliflower is tender.',
        'Stir in spinach until wilted. Season with salt. Serve over rice.',
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 30,
      numOfServings: 4,
      difficulty: 'Medium',
      proteinTypes: ['tofu', 'other'],
      mealTypes: ['dinner'],
      cookingMethods: ['stove'],
      dietaryTags: ['vegetarian', 'healthy'],
      tags: ['vegetarian', 'curry', 'comfort food'],
    },
    {
      name: 'Banana Pancakes',
      description: 'Fluffy pancakes with mashed banana and a hint of cinnamon, perfect for weekend breakfast.',
      ingredients: [
        { name: 'flour', amount: '1.5', unit: 'cups' },
        { name: 'ripe bananas', amount: '2', unit: 'medium' },
        { name: 'milk', amount: '1', unit: 'cup' },
        { name: 'egg', amount: '1', unit: 'whole' },
        { name: 'baking powder', amount: '2', unit: 'tsp' },
        { name: 'cinnamon', amount: '1/2', unit: 'tsp' },
        { name: 'maple syrup', amount: 'to serve', unit: '' },
      ],
      instructions: [
        'Mash bananas in a bowl. Add egg and milk; mix. In another bowl, mix flour, baking powder, and cinnamon.',
        'Combine wet and dry ingredients; do not overmix. Let rest 5 minutes.',
        'Heat a lightly oiled griddle over medium. Pour 1/4 cup batter per pancake. Cook until bubbles form, then flip.',
        'Serve with maple syrup and extra banana slices.',
      ],
      prepTimeMinutes: 10,
      cookTimeMinutes: 15,
      numOfServings: 4,
      difficulty: 'Easy',
      proteinTypes: ['other'],
      mealTypes: ['breakfast'],
      cookingMethods: ['stove'],
      dietaryTags: [],
      tags: ['breakfast', 'weekend'],
    },
    {
      name: 'Chocolate Brownies',
      description: 'Fudgy, dense chocolate brownies with a crackly top and rich cocoa flavor.',
      ingredients: [
        { name: 'butter', amount: '1/2', unit: 'cup' },
        { name: 'sugar', amount: '1', unit: 'cup' },
        { name: 'cocoa powder', amount: '1/3', unit: 'cup' },
        { name: 'eggs', amount: '2', unit: 'whole' },
        { name: 'flour', amount: '1/2', unit: 'cup' },
        { name: 'vanilla extract', amount: '1', unit: 'tsp' },
        { name: 'salt', amount: '1/4', unit: 'tsp' },
      ],
      instructions: [
        'Preheat oven to 350°F. Grease an 8x8 pan. Melt butter and mix with sugar and cocoa until smooth.',
        'Beat in eggs and vanilla. Add flour and salt; stir until just combined. Do not overmix.',
        'Pour into pan. Bake 25–30 minutes until set but still fudgy in the center.',
        'Cool in pan, then cut into squares.',
      ],
      prepTimeMinutes: 10,
      cookTimeMinutes: 30,
      numOfServings: 9,
      difficulty: 'Easy',
      proteinTypes: ['other'],
      mealTypes: ['dessert', 'snack'],
      cookingMethods: ['oven'],
      dietaryTags: [],
      tags: ['dessert', 'chocolate', 'baking'],
    },
  ];

  return recipes.map((r, i) => ({ ...r, id: `${idPrefix}${i}` }));
}
