import { Recipe } from './types';

export const defaultRecipes: Recipe[] = [
  {
    id: 'default-1',
    name: 'Garlic Butter Chicken',
    description: 'Juicy pan-seared chicken breasts in a rich garlic butter sauce. Quick, easy, and packed with flavor.',
    ingredients: [
      { name: 'chicken breasts', amount: '2', unit: 'lbs' },
      { name: 'butter', amount: '3', unit: 'tbsp' },
      { name: 'garlic', amount: '4', unit: 'cloves' },
      { name: 'chicken broth', amount: '1/2', unit: 'cup' },
      { name: 'fresh parsley', amount: '2', unit: 'tbsp' },
      { name: 'salt and pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Season chicken with salt and pepper on both sides.',
      'Melt 2 tbsp butter in a large skillet over medium-high heat.',
      'Sear chicken 6–7 minutes per side until golden and cooked through. Remove and set aside.',
      'Add remaining butter and minced garlic to the pan; cook 1 minute.',
      'Pour in chicken broth and simmer 2 minutes, scraping up any browned bits.',
      'Return chicken to pan, spoon sauce over top, and garnish with parsley.',
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    numOfServings: 4,
    difficulty: 'Easy',
    proteinTypes: ['chicken'],
    mealTypes: ['dinner'],
    cookingMethods: ['stove'],
    dietaryTags: [],
    tags: ['quick', 'weeknight'],
  },
  {
    id: 'default-2',
    name: 'Beef Tacos',
    description: 'Classic ground beef tacos with a homemade spice blend, topped with fresh salsa and shredded cheese.',
    ingredients: [
      { name: 'ground beef', amount: '1', unit: 'lb' },
      { name: 'taco shells', amount: '8', unit: 'shells' },
      { name: 'chili powder', amount: '1', unit: 'tsp' },
      { name: 'cumin', amount: '1/2', unit: 'tsp' },
      { name: 'garlic powder', amount: '1/2', unit: 'tsp' },
      { name: 'shredded cheddar', amount: '1', unit: 'cup' },
      { name: 'salsa', amount: '1/2', unit: 'cup' },
      { name: 'sour cream', amount: '1/4', unit: 'cup' },
    ],
    instructions: [
      'Brown ground beef in a skillet over medium heat; drain excess fat.',
      'Stir in chili powder, cumin, garlic powder, salt, and 1/4 cup water.',
      'Simmer 5 minutes until sauce thickens.',
      'Warm taco shells per package instructions.',
      'Fill shells with beef and top with cheese, salsa, and sour cream.',
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    numOfServings: 4,
    difficulty: 'Easy',
    proteinTypes: ['beef'],
    mealTypes: ['dinner'],
    cookingMethods: ['stove'],
    dietaryTags: [],
    tags: ['quick', 'family-friendly'],
  },
  {
    id: 'default-3',
    name: 'Veggie Stir Fry with Tofu',
    description: 'Crispy tofu and colorful vegetables tossed in a savory ginger-soy sauce over steamed rice.',
    ingredients: [
      { name: 'firm tofu', amount: '14', unit: 'oz' },
      { name: 'broccoli florets', amount: '2', unit: 'cups' },
      { name: 'bell pepper', amount: '1', unit: 'large' },
      { name: 'snap peas', amount: '1', unit: 'cup' },
      { name: 'soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'fresh ginger', amount: '1', unit: 'tsp' },
      { name: 'garlic', amount: '2', unit: 'cloves' },
      { name: 'cooked rice', amount: '2', unit: 'cups' },
    ],
    instructions: [
      'Press tofu dry and cut into 1-inch cubes.',
      'Pan-fry tofu in oil over medium-high heat until golden on all sides, about 8 minutes. Set aside.',
      'In the same pan, stir-fry garlic and ginger 30 seconds.',
      'Add broccoli, bell pepper, and snap peas; cook 4–5 minutes.',
      'Return tofu, pour in soy sauce and sesame oil, toss to combine.',
      'Serve over steamed rice.',
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    numOfServings: 3,
    difficulty: 'Easy',
    proteinTypes: ['tofu'],
    mealTypes: ['dinner', 'lunch'],
    cookingMethods: ['stove'],
    dietaryTags: ['vegetarian', 'vegan'],
    tags: ['healthy', 'vegetarian'],
  },
  {
    id: 'default-4',
    name: 'Baked Lemon Herb Salmon',
    description: 'Tender oven-baked salmon fillets with lemon, dill, and olive oil — ready in under 25 minutes.',
    ingredients: [
      { name: 'salmon fillets', amount: '4', unit: 'pieces' },
      { name: 'lemon', amount: '1', unit: 'large' },
      { name: 'olive oil', amount: '2', unit: 'tbsp' },
      { name: 'fresh dill', amount: '2', unit: 'tbsp' },
      { name: 'garlic powder', amount: '1/2', unit: 'tsp' },
      { name: 'salt and pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C). Line a baking sheet with foil.',
      'Place salmon fillets on the sheet and drizzle with olive oil.',
      'Season with garlic powder, salt, pepper, and dill.',
      'Lay lemon slices on top of each fillet.',
      'Bake 12–15 minutes until salmon flakes easily with a fork.',
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    numOfServings: 4,
    difficulty: 'Easy',
    proteinTypes: ['fish'],
    mealTypes: ['dinner'],
    cookingMethods: ['oven'],
    dietaryTags: ['healthy'],
    tags: ['healthy', 'quick'],
  },
  {
    id: 'default-5',
    name: 'Slow Cooker Pulled Pork',
    description: 'Fall-apart tender pulled pork slow-cooked all day in a smoky BBQ sauce — perfect for sandwiches.',
    ingredients: [
      { name: 'pork shoulder', amount: '3', unit: 'lbs' },
      { name: 'BBQ sauce', amount: '1', unit: 'cup' },
      { name: 'apple cider vinegar', amount: '2', unit: 'tbsp' },
      { name: 'brown sugar', amount: '2', unit: 'tbsp' },
      { name: 'smoked paprika', amount: '1', unit: 'tsp' },
      { name: 'garlic powder', amount: '1', unit: 'tsp' },
      { name: 'onion powder', amount: '1', unit: 'tsp' },
      { name: 'burger buns', amount: '8', unit: 'buns' },
    ],
    instructions: [
      'Mix paprika, garlic powder, onion powder, salt, and pepper; rub all over pork.',
      'Place pork in slow cooker. Mix BBQ sauce, vinegar, and brown sugar; pour over pork.',
      'Cook on low 8 hours or high 4–5 hours until fork-tender.',
      'Remove pork and shred with two forks.',
      'Stir shredded pork back into the juices and serve on buns.',
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 480,
    numOfServings: 8,
    difficulty: 'Easy',
    proteinTypes: ['pork'],
    mealTypes: ['dinner', 'lunch'],
    cookingMethods: ['slow cooker'],
    dietaryTags: [],
    tags: ['meal-prep', 'crowd-pleaser'],
  },
  {
    id: 'default-6',
    name: 'Overnight Oats',
    description: 'Creamy no-cook oats prepared the night before with your choice of toppings — a perfect grab-and-go breakfast.',
    ingredients: [
      { name: 'rolled oats', amount: '1/2', unit: 'cup' },
      { name: 'milk or almond milk', amount: '1/2', unit: 'cup' },
      { name: 'Greek yogurt', amount: '1/4', unit: 'cup' },
      { name: 'chia seeds', amount: '1', unit: 'tbsp' },
      { name: 'honey', amount: '1', unit: 'tbsp' },
      { name: 'fresh berries', amount: '1/2', unit: 'cup' },
    ],
    instructions: [
      'Combine oats, milk, yogurt, chia seeds, and honey in a jar or container.',
      'Stir well to combine.',
      'Seal and refrigerate overnight (at least 6 hours).',
      'In the morning, top with fresh berries and enjoy cold.',
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    numOfServings: 1,
    difficulty: 'Easy',
    proteinTypes: ['other'],
    mealTypes: ['breakfast'],
    cookingMethods: ['no bake'],
    dietaryTags: ['vegetarian', 'healthy'],
    tags: ['meal-prep', 'quick', 'healthy'],
  },
  {
    id: 'default-7',
    name: 'Chicken and Vegetable Soup',
    description: 'A hearty, comforting chicken soup loaded with vegetables — great for meal prep and freezer-friendly.',
    ingredients: [
      { name: 'chicken thighs', amount: '1.5', unit: 'lbs' },
      { name: 'carrots', amount: '3', unit: 'medium' },
      { name: 'celery stalks', amount: '3', unit: 'stalks' },
      { name: 'onion', amount: '1', unit: 'large' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'chicken broth', amount: '6', unit: 'cups' },
      { name: 'egg noodles', amount: '2', unit: 'cups' },
      { name: 'thyme', amount: '1', unit: 'tsp' },
      { name: 'bay leaf', amount: '1', unit: 'leaf' },
    ],
    instructions: [
      'Dice onion, carrots, and celery. Mince garlic.',
      'Sauté onion and garlic in a large pot over medium heat until soft.',
      'Add carrots, celery, thyme, and bay leaf; cook 3 minutes.',
      'Pour in broth and add chicken thighs. Bring to a boil.',
      'Reduce heat and simmer 25 minutes until chicken is cooked through.',
      'Remove chicken, shred with forks, and return to pot.',
      'Add egg noodles and cook 8 minutes until tender. Remove bay leaf and serve.',
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    numOfServings: 6,
    difficulty: 'Easy',
    proteinTypes: ['chicken'],
    mealTypes: ['dinner', 'lunch'],
    cookingMethods: ['stove'],
    dietaryTags: ['healthy'],
    tags: ['meal-prep', 'comfort-food'],
  },
  {
    id: 'default-8',
    name: 'Beef and Broccoli',
    description: 'Restaurant-style beef and broccoli in a savory brown sauce, ready in 30 minutes.',
    ingredients: [
      { name: 'flank steak', amount: '1', unit: 'lb' },
      { name: 'broccoli florets', amount: '3', unit: 'cups' },
      { name: 'soy sauce', amount: '1/4', unit: 'cup' },
      { name: 'oyster sauce', amount: '2', unit: 'tbsp' },
      { name: 'sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'cornstarch', amount: '2', unit: 'tbsp' },
      { name: 'garlic', amount: '3', unit: 'cloves' },
      { name: 'cooked rice', amount: '2', unit: 'cups' },
    ],
    instructions: [
      'Slice steak thinly against the grain. Toss with 1 tbsp soy sauce and 1 tbsp cornstarch.',
      'Blanch broccoli in boiling water 2 minutes; drain.',
      'Mix remaining soy sauce, oyster sauce, sesame oil, and 1 tbsp cornstarch in a bowl.',
      'Stir-fry beef in a hot wok over high heat 2–3 minutes; remove.',
      'Stir-fry garlic 30 seconds, add broccoli and cook 2 minutes.',
      'Return beef, pour in sauce, toss everything together and serve over rice.',
    ],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    numOfServings: 4,
    difficulty: 'Medium',
    proteinTypes: ['beef'],
    mealTypes: ['dinner'],
    cookingMethods: ['stove'],
    dietaryTags: [],
    tags: ['takeout-style', 'weeknight'],
  },
  {
    id: 'default-9',
    name: 'Avocado Toast with Egg',
    description: 'Creamy mashed avocado on toasted sourdough topped with a perfectly fried egg and chili flakes.',
    ingredients: [
      { name: 'sourdough bread', amount: '2', unit: 'slices' },
      { name: 'ripe avocado', amount: '1', unit: 'large' },
      { name: 'eggs', amount: '2', unit: 'large' },
      { name: 'lemon juice', amount: '1', unit: 'tsp' },
      { name: 'red chili flakes', amount: '1/4', unit: 'tsp' },
      { name: 'salt and pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Toast bread until golden and crisp.',
      'Mash avocado with lemon juice, salt, and pepper.',
      'Fry eggs in a non-stick pan to your liking (sunny-side up recommended).',
      'Spread avocado on toast, top each with a fried egg, and sprinkle chili flakes.',
    ],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    numOfServings: 2,
    difficulty: 'Easy',
    proteinTypes: ['other'],
    mealTypes: ['breakfast', 'lunch'],
    cookingMethods: ['stove'],
    dietaryTags: ['vegetarian', 'healthy'],
    tags: ['quick', 'healthy'],
  },
  {
    id: 'default-10',
    name: 'Sheet Pan Sausage and Veggies',
    description: 'One-pan dinner with Italian sausage, bell peppers, zucchini, and onions roasted to perfection.',
    ingredients: [
      { name: 'Italian sausage links', amount: '4', unit: 'links' },
      { name: 'bell peppers', amount: '2', unit: 'large' },
      { name: 'zucchini', amount: '2', unit: 'medium' },
      { name: 'red onion', amount: '1', unit: 'large' },
      { name: 'olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Italian seasoning', amount: '1', unit: 'tsp' },
      { name: 'garlic powder', amount: '1/2', unit: 'tsp' },
      { name: 'salt and pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Preheat oven to 400°F (200°C).',
      'Slice sausages into 1-inch pieces. Chop peppers, zucchini, and onion into similar-sized chunks.',
      'Toss everything with olive oil, Italian seasoning, garlic powder, salt, and pepper.',
      'Spread in a single layer on a large sheet pan.',
      'Roast 25–30 minutes, tossing halfway, until sausage is cooked and veggies are slightly caramelized.',
    ],
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    numOfServings: 4,
    difficulty: 'Easy',
    proteinTypes: ['pork'],
    mealTypes: ['dinner'],
    cookingMethods: ['oven'],
    dietaryTags: [],
    tags: ['one-pan', 'easy-cleanup'],
  },
];
